{% set version = "5.3.0" %}

package:
  name: rise
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rise/rise-{{ version }}.tar.gz
  sha256: b34cc01ff85e47f386456ac4cb0659dcb2fb482c6db05feb5218d43580fea519

build:
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed .
    - jupyter nbextension install --sys-prefix --py rise

requirements:
  build:
    - python
    - pip >=10.0.1
    - notebook >=5.5.0
  run:
    - python
    - notebook >=5.5.0

test:
  imports:
    - rise

about:
  home: https://github.com/damianavila/RISE
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'RISE: Live Reveal.js Jupyter/IPython Slideshow Extension'
  description:  Reveal.js - Jupyter/IPython Slideshow Extension, also known as live_reveal. Quickly turn your Jupyter Notebooks into a live presentation.  
  doc_url: http://rise.readthedocs.io/en/latest
  dev_url: https://github.com/damianavila/RISE

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - damianavila
    - parmentelat
    - Juanlu001
