# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "aLxqhfZR4P96ks126jo99/Jp3gp8NF54tbQejE12ZbEGJZOp7RQCqSterXWGBf4tvbWI1YMDAagCwMsmwQO2kmIw2pGgLSHcuq3I2lYt5IABbWus3fpg1yEekjfesKhidGOu6jymkK5V+TEW8bFIf9yaubzcKiWu+nzEWbqmu/3QME3NmEnp5KfqIa9n8jhglfcq3WoiSpJtxYopAnP1i7D4B3eda+8iDArs+J1tEdPmWpq9h9OxMr4cLNaJAx/nDtNt4agd+IE82H8ZIgseX4lGIXnWNjV3uY97zZvDiXB+iqMOB9dEPVkWmdxXHDfju9Yj+fERNaR7zFrIeCvFEMhK2m+h+S7IhuWys+LlyJvOZxF0e7VSSRxhlEU5JQ/oDXIUuWfHIhKpfxY9D+OtXGv9b1yVHzSOWPhwMg3DF6+v2GPothu/iA6Lc4uTBL0GGfRPnSJygxLNRtdMFE2xoqMjRTERKyf1skpISECDlJb1Ij32P9/2UWS+2rqMqVWVhhfAimR7eHoV9lYWjPohHZ5NSQf7lVIawzxeZzmKOi+X9KxsDE8dqHqU1rQyUoqYN65uV/tN0G8HncjbIab/jQPAseiozzyN6uB+jvV416Cq/UQIel7VZ2+FZyIUJK4Ee1uc0PQ4hBzH+p0MhD2HcipZmxrmwCg8JRSQDQIgUAc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
