appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: aLxqhfZR4P96ks126jo99/Jp3gp8NF54tbQejE12ZbEGJZOp7RQCqSterXWGBf4tvbWI1YMDAagCwMsmwQO2kmIw2pGgLSHcuq3I2lYt5IABbWus3fpg1yEekjfesKhidGOu6jymkK5V+TEW8bFIf9yaubzcKiWu+nzEWbqmu/3QME3NmEnp5KfqIa9n8jhglfcq3WoiSpJtxYopAnP1i7D4B3eda+8iDArs+J1tEdPmWpq9h9OxMr4cLNaJAx/nDtNt4agd+IE82H8ZIgseX4lGIXnWNjV3uY97zZvDiXB+iqMOB9dEPVkWmdxXHDfju9Yj+fERNaR7zFrIeCvFEMhK2m+h+S7IhuWys+LlyJvOZxF0e7VSSRxhlEU5JQ/oDXIUuWfHIhKpfxY9D+OtXGv9b1yVHzSOWPhwMg3DF6+v2GPothu/iA6Lc4uTBL0GGfRPnSJygxLNRtdMFE2xoqMjRTERKyf1skpISECDlJb1Ij32P9/2UWS+2rqMqVWVhhfAimR7eHoV9lYWjPohHZ5NSQf7lVIawzxeZzmKOi+X9KxsDE8dqHqU1rQyUoqYN65uV/tN0G8HncjbIab/jQPAseiozzyN6uB+jvV416Cq/UQIel7VZ2+FZyIUJK4Ee1uc0PQ4hBzH+p0MhD2HcipZmxrmwCg8JRSQDQIgUAc=}
provider:
  win: azure
